name: test
on: [push]
jobs:
  test:
    name: GitHub Actions test
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: GitHubActionsMysql
          MYSQL_DATABASE: github_actions_db
          MYSQL_USER: github_actions_user
          MYSQL_PASSWORD: GitHubActionsMysql
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - name: Run Jest
        run: yarn test

  slack-notification:
    if: always()
    needs:  test
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Slack Notification
        uses: sonots/slack-notice-action@v3
        with:
          title: test (${{ github.event.repository.name }})
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.MY_GITHUB_CHANNEL_WEBHOOK_URL }}

